module.exports = {
  NO_MOVE_OK: 'NO_MOVE_OK',
  JOB_UPGRADE: 'JOB_UPGRADE',
  JOB_HARVESTER: 'JOB_HARVESTER',
  JOB_ROAD_PLANNER: 'ROADPLANNER',
  JOB_BUILDER: 'BUILDER',
  JOB_CIV_ENG: 'CIV_ENG',
  STATUS_START: 'START',
  STATUS_BUILD: 'BUILD',
  STATUS_COMPLETE: 'COMPLETE'
}
